SELECT * FROM employees WHERE department_id = 40;
SELECT last_name, salary FROM employees WHERE job_id  = 'IT_PROG';
SELECT last_name, email FROM employees WHERE hire_date  = '07-JUN-02';
SELECT * FROM employees WHERE hire_date > '01-JUN-06' AND department_id > 60;
SELECT * FROM employees WHERE hire_date BETWEEN '01-JUN-07' AND '01-DEC-07';
SELECT * FROM employees WHERE salary < 5000;
SELECT COUNT(*) FROM employees WHERE salary < 5000;
SELECT * FROM employees WHERE salary > 10000 AND salary < 15000;
SELECT * FROM employees WHERE manager_id = 100 OR manager_id = 101 OR manager_id = 201;
SELECT * FROM employees WHERE manager_id IN (100, 101, 201);
SELECT * FROM employees WHERE job_id NOT IN ('IT_PROG', 'SA_REP', 'FI_ACCOUNT');
SELECT * FROM employees WHERE last_name LIKE 'K%';
SELECT * FROM employees WHERE first_name LIKE '%R';
SELECT last_name, email, phone_number FROM employees WHERE first_name LIKE 'S%' OR first_name LIKE 'J%';
SELECT * FROM employees WHERE SUBSTRING(first_name, 2, 1) = 'o';
SELECT * FROM employees WHERE department_id IS NULL;
SELECT COUNT(*) FROM employees WHERE manager_id IS NULL;
SELECT * FROM employees WHERE commission_pct IS NULL;
SELECT * FROM employees WHERE job_id = 'SA_REP' AND salary > 10000;
SELECT * FROM employees WHERE job_id = 'SA_REP' OR salary < 10000;
SELECT * FROM employees WHERE job_id = 'SA_REP' OR (job_id = 'AD_PRES' AND salary > 15000);
SELECT * FROM employees WHERE (job_id = 'SA_REP' OR job_id = 'AD_PRES') AND salary > 15000;
SELECT * FROM employees ORDER BY email DESC;
SELECT * FROM employees ORDER BY employee_id;
SELECT * FROM employees ORDER BY employee_id DESC;
SELECT job_id, first_name, hire_date FROM employees ORDER BY job_id DESC, first_name;
SELECT * FROM employees ORDER BY 6;
