apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-assignment-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: bold-sammet
        image: ashnahkhalidkhan00210/assignment3:tag_number_${BUILD_NUMBER}  # This will be updated by Jenkins
        ports:
        - containerPort: 3000