pipeline {
    agent any 
    stages {
        stage('Checkout SCM') {
            steps {  
                git branch: 'main', credentialsId: 'github_id', url: 'https://github.com/AshnahKhalidKhan/CheckSQL.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "ashnahkhalidkhan00210/assignment3:tag_number_${env.BUILD_NUMBER}"
                    sh "docker build -t ${imageName} ./lazychex"
                }
            }
        }
        stage('Push to DockerHub') {
            steps {
                script {
                    def imageName = "ashnahkhalidkhan00210/assignment3:tag_number_${env.BUILD_NUMBER}"
                    withCredentials([usernamePassword(credentialsId: 'dockerhub_id', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                        // echo "$DOCKERHUB_PASS"
                        // sh "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS docker.io"
                        // sh "docker login -u $DOCKERHUB_USER --password-stdin docker.io"
                        sh "echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin docker.io"
                    }
                    sh "docker push ${imageName}"
                    sh "docker logout"
                }
            }
        }
        // stage('Deploy to Kubernetes') {
        //     steps {
        //         script {
        //             // Update the image in the deployment YAML file
        //             def imageName = "muhammadhur/tutorial:${env.BUILD_NUMBER}"
        //             sh "sed -i 's|muhammadhur/tutorial:latest|${imageName}|' ./deployment.yaml"
        //             // Apply the deployment
        //             withCredentials([file(credentialsId: 'kube', variable: 'KUBECONFIG')]) {
        //                 sh 'kubectl apply -f ./deployment.yaml'
        //             }
        //         }
        //     }
        // }
    }
}